<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="BPMN"
    nsURI="http://de.htwg.2012.bpmn" nsPrefix="bpmn">
  <eClassifiers xsi:type="ecore:EClass" name="BPMNModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelElements" upperBound="-1"
        eType="#//BPMNModelElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventStartDefault" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventEndDefault" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventEndUsed" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventMail" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventMailDash" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventMailDouble" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventMailDoubleDash" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventMailInvertDouble" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventMailInvertBold" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventTimerDefault" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventTimerDash" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventTimerDouble" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventTimerDoubleDash" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventEskalationStart" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventEskalationDash" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventEskalationDouble" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventEskalationDoubelDash" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventEskalationDoubelInvert" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventEskalationBoldInvert" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventIfDefault" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventIfDash" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventIfDouble" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventIfDoubleDash" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventLinkEntered" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventLinkTriggerd" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventErrorDefault" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventErrorDouble" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventErrorBoldInvert" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventCancelDouble" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventCancelBoldInvert" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventCompensationDefault" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventCompensationDouble" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventCompensationDoubleInvert" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventCompensationBoldInvert" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventSignalDefault" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventSignalDash" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventSignalDouble" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventSignalDoubleDash" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventSignalDoubleInvert" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventSignalBoldInvert" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventMultiDefault" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventMultiDash" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventMultiDouble" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventMultiDoubleDash" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventMultiDoubleInvert" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventMultiBoldInvert" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventParallelDefault" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventParallelDash" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventParallelDouble" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventParallelDoubleDash" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNEventTermination" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNActivityTask" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNActivityTransaction" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNActivityEventSubProcess" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNActivityCallActivity" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNGatewayXOR1" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNGatewayXOR2" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNGatewayEvent" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNGatewayAnd" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNGatewayOR" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNGatewayComplex" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNGatewayXEvent" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNGatewayAndEvent" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNConversationDefault" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNConversationBold" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNOneData" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNListData" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNDataStorage" eSuperTypes="#//BPMNModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNSequenceFlow" eSuperTypes="#//BPMNModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="formElement" eType="#//BPMNModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toElement" eType="#//BPMNModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNDefaultFlow" eSuperTypes="#//BPMNModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="formElement" eType="#//BPMNModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toElement" eType="#//BPMNModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNConditionalFlow" eSuperTypes="#//BPMNModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="formElement" eType="#//BPMNModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toElement" eType="#//BPMNModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNDataAssoziation" eSuperTypes="#//BPMNModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="formElement" eType="#//BPMNModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toElement" eType="#//BPMNModelElement"/>
  </eClassifiers>
</ecore:EPackage>
