/*
* generated by Xtext
*/
package org.eclipselabs.spray2.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class Spray2UiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipselabs.spray2.xtext.ui.internal.Spray2Activator.getInstance().getInjector("org.eclipselabs.spray2.xtext.Spray2");
	}
	
}
