/*
 * generated by Xtext
 */
package org.eclipselabs.spray.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ShapesUiModule extends org.eclipselabs.spray.ui.AbstractShapesUiModule {
	public ShapesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
