<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="spray"
    nsURI="http://code.google.com/a/eclipselabs.org/p/spray" nsPrefix="spray">
  <eClassifiers xsi:type="ecore:EClass" name="Diagram" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaClasses" upperBound="-1"
        eType="#//MetaClass" containment="true" eOpposite="#//MetaClass/diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviourGroups" upperBound="-1"
        eType="#//BehaviorGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelType" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ShapeInSpray" abstract="true" eSuperTypes="#//SprayElement #//AliasableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="represents" eType="#//MetaClass"
        eOpposite="#//MetaClass/representedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layout" eType="#//Layout"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Layout">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rounded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cornerHeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="10"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cornerWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="10"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="figure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Rectangle" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="italic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lineColor" eType="#//ColorInSpray"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textColor" eType="#//ColorInSpray"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fillColor" eType="#//ColorInSpray"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RectangleInSpray" eSuperTypes="#//ShapeInSpray"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerInSpray" eSuperTypes="#//ShapeInSpray">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parts" upperBound="-1"
        eType="#//SprayElement" containment="true" eOpposite="#//SprayElement/container"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="list" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="horizontal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextInSpray" eSuperTypes="#//ShapeInSpray">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        transient="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SprayElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//ContainerInSpray"
        eOpposite="#//ContainerInSpray/parts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionInSpray" eSuperTypes="#//ShapeInSpray">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromLabel" eType="#//TextInSpray"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toLabel" eType="#//TextInSpray"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectionLabel" eType="#//TextInSpray"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetaClass" eSuperTypes="#//AliasableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="representedBy" eType="#//ShapeInSpray"
        containment="true" eOpposite="#//ShapeInSpray/represents"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagram" eType="#//Diagram"
        eOpposite="#//Diagram/metaClasses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="#//MetaReference" containment="true" eOpposite="#//MetaReference/metaClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="icon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviors" upperBound="-1"
        eType="#//Behavior" containment="true" eOpposite="#//Behavior/metaClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviorGroups" upperBound="-1"
        eType="#//BehaviorGroup"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasStyle" eType="ecore:EClass ../../org.eclipselabs.spray.styles/src-gen/org/eclipselabs/spray/styles/Style.ecore#//Style"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetaReference" eSuperTypes="#//SprayElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="representedBy" eType="#//ConnectionInSpray"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaClass" eType="#//MetaClass"
        eOpposite="#//MetaClass/references"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" eType="#//TextInSpray"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelProperty" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LineInSpray" eSuperTypes="#//ShapeInSpray"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Figure"/>
  <eClassifiers xsi:type="ecore:EClass" name="Behavior" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaClass" eType="#//MetaClass"
        eOpposite="#//MetaClass/behaviors"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paletteCompartment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateBehavior" eSuperTypes="#//Behavior">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containmentReference" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="askFor" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomBehavior" eSuperTypes="#//Behavior"/>
  <eClassifiers xsi:type="ecore:EClass" name="BehaviorGroup" eSuperTypes="#//SprayElement #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviors" upperBound="-1"
        eType="#//Behavior" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColorInSpray" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ColorConstantRef" eSuperTypes="#//ColorInSpray">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmTypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmField"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RGBColor" eSuperTypes="#//ColorInSpray">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="red" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="green" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AliasableElement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ShapeFromDsl" eSuperTypes="#//ShapeInSpray">
    <eStructuralFeatures xsi:type="ecore:EReference" name="shape" eType="ecore:EClass ../../org.eclipselabs.spray.shapes/src-gen/org/eclipselabs/spray/shapes/Shape.ecore#//ShapeDefinition"/>
  </eClassifiers>
</ecore:EPackage>
