/*
 * generated by Xtext
 */
package org.eclipselabs.spray2.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Spray2UiModule extends org.eclipselabs.spray2.xtext.ui.AbstractSpray2UiModule {
	public Spray2UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
