/*
 * generated by Xtext
 */
package org.eclipselabs.spray2.xtext.ui.contentassist;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Set;

import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.IFolder;
import org.eclipse.core.resources.IResource;
import org.eclipse.core.resources.IResourceVisitor;
import org.eclipse.core.resources.IWorkspaceRoot;
import org.eclipse.core.runtime.CoreException;
import org.eclipse.core.runtime.IPath;
import org.eclipse.core.runtime.Path;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.graphiti.features.custom.ICustomFeature;
import org.eclipse.jface.resource.ImageDescriptor;
import org.eclipse.jface.text.contentassist.ICompletionProposal;
import org.eclipse.jface.viewers.StyledString;
import org.eclipse.swt.graphics.Image;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.common.types.JvmType;
import org.eclipse.xtext.common.types.access.IJvmTypeProvider;
import org.eclipse.xtext.common.types.xtext.ui.ITypesProposalProvider;
import org.eclipse.xtext.common.types.xtext.ui.ITypesProposalProvider.Filter;
import org.eclipse.xtext.common.types.xtext.ui.TypeMatchFilters;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;
import org.eclipselabs.spray.runtime.graphiti.shape.ISprayConnection;
import org.eclipselabs.spray.runtime.graphiti.shape.ISprayShape;
import org.eclipselabs.spray.runtime.graphiti.styles.ISprayStyle;
import org.eclipselabs.spray2.xtext.api.IConstants;
import org.eclipselabs.spray2.xtext.spray2.BehaviorSection;
import org.eclipselabs.spray2.xtext.spray2.EdgeFigureSection;
import org.eclipselabs.spray2.xtext.spray2.NodeFigureSection;
import org.eclipselabs.spray2.xtext.spray2.Spray2Package;
import org.eclipselabs.spray2.xtext.spray2.SprayStyleRef;

import com.google.inject.Inject;
import com.google.inject.name.Named;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class Spray2ProposalProvider extends AbstractSpray2ProposalProvider {

    @Inject
    private IWorkspaceRoot   root;
    @Inject
    @Named(IConstants.NAME_VALID_ICON_FILE_EXTENSIONS)
    private Set              validIconFileExtensions;
    @Inject
    ITypesProposalProvider   proposalProvider;
    @Inject
    IJvmTypeProvider.Factory typeProviderFactory;

    @Override
    public void complete_JvmTypeReference(EObject model, RuleCall ruleCall, ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
        IJvmTypeProvider typeProvider = typeProviderFactory.findOrCreateTypeProvider(model.eResource().getResourceSet());
        Filter filter = TypeMatchFilters.and(TypeMatchFilters.isPublic(), TypeMatchFilters.canInstantiate());
        if (model instanceof SprayStyleRef) {
            JvmType superType = typeProvider.findTypeByName(ISprayStyle.class.getName());
            proposalProvider.createSubTypeProposals(superType, this, context, Spray2Package.Literals.SPRAY_STYLE_REF__STYLE, filter, acceptor);
        }
        if (model instanceof NodeFigureSection) {
            JvmType superType = typeProvider.findTypeByName(ISprayShape.class.getName());
            proposalProvider.createSubTypeProposals(superType, this, context, Spray2Package.Literals.NODE_FIGURE_SECTION__SHAPE_REF, filter, acceptor);
        }
        if (model instanceof EdgeFigureSection) {
            JvmType superType = typeProvider.findTypeByName(ISprayConnection.class.getName());
            proposalProvider.createSubTypeProposals(superType, this, context, Spray2Package.Literals.EDGE_FIGURE_SECTION__SHAPE_REF, filter, acceptor);
        }
        if (model instanceof BehaviorSection) {
            JvmType superType = typeProvider.findTypeByName(ICustomFeature.class.getName());
            proposalProvider.createSubTypeProposals(superType, this, context, Spray2Package.Literals.NODE_FIGURE_SECTION__SHAPE_REF, filter, acceptor);
        }
        super.complete_JvmTypeReference(model, ruleCall, context, acceptor);
    }

    @Override
    public void completeToolingSection_Icon(EObject model, Assignment assignment, final ContentAssistContext context, final ICompletionProposalAcceptor acceptor) {
        URI uri = model.eResource().getURI();
        if (!uri.isPlatformResource()) {
            return;
        }
        final String projectName = uri.segment(1);
        IPath iconFolderPath = new Path(projectName).append("icons");
        IFolder folder = root.getFolder(iconFolderPath);
        if (!folder.exists()) {
            return;
        }
        try {
            folder.accept(new IResourceVisitor() {
                @Override
                public boolean visit(IResource resource) {
                    if (resource instanceof IFile) {
                        IFile file = (IFile) resource;
                        if (validIconFileExtensions.contains(file.getFileExtension())) {
                            final String proposalText = "\"" + file.getFullPath().removeFirstSegments(2).toString() + "\"";
                            final StyledString displayString = new StyledString(file.getFullPath().removeFirstSegments(2).toString());
                            final Image image = getImage(file.getLocation());
                            ICompletionProposal proposal = doCreateProposal(proposalText, displayString, image, 0, context);
                            acceptor.accept(proposal);
                        }
                    }
                    return true;
                }
            });
        } catch (CoreException e) {
            ; // ignore
        }
    }

    protected Image getImage(IPath path) {
        URL url = null;
        try {
            url = path.toFile().toURL();
        } catch (MalformedURLException e) {
            return null;
        }
        final Image image = ImageDescriptor.createFromURL(url).createImage();
        return image;
    }
}
