/*
* generated by Xtext
*/
package org.eclipselabs.spray2.xtext.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class Spray2OutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
