/*
 * generated by Xtext
 */
package org.eclipselabs.spray2.xtext;

import org.eclipselabs.spray2.xtext.scoping.Spray2ScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Spray2RuntimeModule extends org.eclipselabs.spray2.xtext.AbstractSpray2RuntimeModule {

    public Class<? extends org.eclipse.xtext.scoping.IScopeProvider> bindIScopeProvider() {
        return Spray2ScopeProvider.class;
    }

}
