/*
 * generated by Xtext
 */
package org.eclipselabs.spray.shapes.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.ui.views.contentoutline.IContentOutlinePage;
import org.eclipse.xtext.ui.editor.model.TokenTypeToStringMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipselabs.spray.shapes.ui.outline.ShapeOutlinePage;
import org.eclipselabs.spray.shapes.ui.syntaxcoloring.ShapeHighlightingConfiguration;
import org.eclipselabs.spray.shapes.ui.syntaxcoloring.ShapeTokenToAttributeIdMapper;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ShapeUiModule extends org.eclipselabs.spray.shapes.ui.AbstractShapeUiModule {
    public ShapeUiModule(AbstractUIPlugin plugin) {
        super(plugin);
    }

    public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
        return ShapeTokenToAttributeIdMapper.class;
    }

    @Override
    public void configure(Binder binder) {
        super.configure(binder);
        binder.bind(TokenTypeToStringMapper.class).to(ShapeTokenToAttributeIdMapper.class);
    }

    public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
        return ShapeHighlightingConfiguration.class;
    }

    @Override
    public Class<? extends IContentOutlinePage> bindIContentOutlinePage() {
        return ShapeOutlinePage.class;
    }

}
