/*
 * generated by Xtext
 */
package org.eclipselabs.spray.shapes.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ShapeUiModule extends org.eclipselabs.spray.shapes.ui.AbstractShapeUiModule {
	public ShapeUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
