/*
 * generated by Xtext
 */
package org.eclipselabs.spray.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class StylesUiModule extends org.eclipselabs.spray.ui.AbstractStylesUiModule {
	public StylesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
