/*
* generated by Xtext
*/
package org.eclipselabs.spray.styles.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class StyleOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
