package org.eclipselabs.spray.generator.graphiti.tests.mod4j.mod4j.features

import org.eclipse.xtext.junit4.InjectWith
import org.eclipselabs.spray.generator.graphiti.tests.AbstractSprayGeneratorTest
import org.eclipselabs.spray.generator.graphiti.tests.SprayTestsInjectorProvider
import org.eclipselabs.xtext.utils.unittesting.XtextRunner2
import org.junit.Test
import org.junit.runner.RunWith

import static org.junit.Assert.*

@RunWith(typeof(XtextRunner2))
@InjectWith(typeof(SprayTestsInjectorProvider))
class Mod4jCreateBusinessClassSuperclassFeatureBaseTest extends AbstractSprayGeneratorTest {

    @Test
    def void test() {
       val fsa = triggerGenerator("mod4j/mod4j-busmod.spray")
       val keyClass = "DEFAULT_OUTPUTorg/eclipselabs/spray/examples/mod4j/features/Mod4jCreateBusinessClassSuperclassFeatureBase.java"
       assertTrue(keyClass + " should have been generated", fsa.files.containsKey(keyClass))
       assertEquals(keyClass + " should have the expected content", fsa.files.get(keyClass).toString, expectedContent.toString)
    }

    def private expectedContent() '''
        /*************************************************************************************
         *
         * Generated by Spray CreateReferenceAsConnectionFeature.xtend
         *
         * This file contains generated and should not be changed.
         * Use the extension point class (the direct subclass of this class) to add manual code
         *
         *************************************************************************************/
        package org.eclipselabs.spray.examples.mod4j.features;
        
        import org.eclipse.emf.common.util.EList;
        import org.eclipse.graphiti.features.IFeatureProvider;
        import org.eclipse.graphiti.features.context.ICreateConnectionContext;
        import org.eclipse.graphiti.features.context.impl.AddConnectionContext;
        import org.eclipse.graphiti.mm.pictograms.Anchor;
        import org.eclipse.graphiti.mm.pictograms.Connection;
        import org.eclipse.graphiti.mm.pictograms.PictogramElement;
        import org.eclipse.graphiti.mm.pictograms.Shape;
        import org.eclipselabs.spray.runtime.graphiti.features.AbstractCreateConnectionFeature;
        import org.eclipselabs.spray.runtime.graphiti.layout.SprayLayoutService;
        import null.BusinessDomainDslPackage;
        import samplepackage.BusinessClass;
        
        
        public abstract class Mod4jCreateBusinessClassSuperclassFeatureBase extends AbstractCreateConnectionFeature {
        
            public Mod4jCreateBusinessClassSuperclassFeatureBase(final IFeatureProvider fp) {
                // set name and description of the creation feature
                this(fp, "superclass", "Create superclass");
            }
            protected Mod4jCreateBusinessClassSuperclassFeatureBase(final IFeatureProvider fp, final String name, final String description) {
                // provide name and description for the UI, e.g. the palette
                super(fp, name, description);
            }
            /**
             * {@inheritDoc}
             */
            @Override
            public boolean canCreate(final ICreateConnectionContext context) {
                // return true if both anchors belong to an EClass of the correct type and those EClasses are not identical
                Anchor targetAnchor = getDslShapeAnchor(context.getTargetPictogramElement());
                Anchor sourceAnchor = getDslShapeAnchor(context.getSourcePictogramElement());
                final BusinessClass source = getBusinessClass(sourceAnchor);
                final BusinessClass target = getSuperclass(targetAnchor);
                if ( (source != null) && (target != null) && (source != target) ) {
                    return true;
                }
                return false;
            }
            /**
             * {@inheritDoc}
             */
            @Override
            public boolean canStartConnection(final ICreateConnectionContext context) {
                // return true if start anchor belongs to a EClass of the right type
                Anchor sourceAnchor = getDslShapeAnchor(context.getSourcePictogramElement());
                final BusinessClass businessClass = (BusinessClass) getBusinessClass(sourceAnchor);
                if (businessClass == null) {
                    return false;
                }
                // single valued reference. can only be started if the reference is not set yet.
                return businessClass.getSuperclass() == null;
            }
                /**
                 * {@inheritDoc}
                 */
                @Override
                public Connection create(final ICreateConnectionContext context) {
                    Connection newConnection = null;
                    Anchor sourceAnchor = getDslShapeAnchor(context.getSourcePictogramElement());
                    Anchor targetAnchor = getDslShapeAnchor(context.getTargetPictogramElement());
            
                    // get EClasses which should be connected
                    final BusinessClass source = getBusinessClass(sourceAnchor);
                    final BusinessClass target = getSuperclass(targetAnchor);
            
                    if (source != null && target != null) {
                        // create new business object
                        setSuperclass(source, target);
                        // add connection for business object
                        final AddConnectionContext addContext = new AddConnectionContext( sourceAnchor, targetAnchor);
                        addContext.setNewObject(source);
                        addContext.putProperty(PROPERTY_REFERENCE, BusinessDomainDslPackage.Literals.BUSINESS_CLASS__SUPERCLASS.getName());
                        // TODO: assume that the target object has a Name property
                //        addContext.putProperty("TARGETOBJECT", target.getName());
                        newConnection = (Connection) getFeatureProvider().addIfPossible(addContext);
                    }
            
                    return newConnection;
                }
            /**
             * Returns the BusinessClass belonging to the anchor, or <code>null</code> if not available.
             */
            protected BusinessClass getBusinessClass(final Anchor anchor) {
                if( anchor != null) {
                    final Object bo = getBusinessObjectForPictogramElement(anchor.getParent());
                    if (anchor != null && bo instanceof BusinessClass) {
                        return (BusinessClass) bo;
                    }
                }
                return null;
            }
            /**
             * Returns the superclass belonging to the anchor, or <code>null</code> if not available.
             */
            protected BusinessClass getSuperclass(final Anchor anchor) {
                if( anchor != null) {
                    final Object bo = getBusinessObjectForPictogramElement(anchor.getParent());
                    if (anchor != null && bo instanceof BusinessClass) {
                        return (BusinessClass) bo;
                    }
                }
                return null;
            }
            /**
             * Creates a superclass .
             */
            protected void setSuperclass(final BusinessClass source, final BusinessClass target) {
                source.setSuperclass(target);
            }
            protected Anchor getDslShapeAnchor(PictogramElement pe) {
                if( pe == null ){
                    return null;
                }
                Shape dslShape = SprayLayoutService.findDslShape(pe);
                if (dslShape != null) {
                    EList<Anchor> anchors = dslShape.getAnchors();
                    if (!anchors.isEmpty()) {
                        return anchors.get(0);
                    }
                }
                return null;
            }
        }
    '''
}
