/*
 * generated by Xtext
 */
package org.eclipselabs.spray.styles.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class StyleUiModule extends org.eclipselabs.spray.styles.ui.AbstractStyleUiModule {
	public StyleUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
